export const CARDS = [
  { id: 1, coupleId: 1, content: "Actual", flipped: false, matched: false, language: "en"},
  { id: 2, coupleId: 1, content: "Real", flipped: false, matched: false, language: "es"},
  { id: 3, coupleId: 2, content: "Actual", flipped: false, matched: false, language: "es"},
  { id: 4, coupleId: 2, content: "Current", flipped: false, matched: false, language: "en"},
  { id: 5, coupleId: 3, content: "Assist", flipped: false, matched: false, language: "en" },
  { id: 6, coupleId: 3, content: "Ayudar", flipped: false, matched: false, language: "es" },
  { id: 7, coupleId: 4, content: "To attend", flipped: false, matched: false, language: "en"},
  { id: 8, coupleId: 4, content: "Asistir", flipped: false, matched: false, language: "es"},
  { id: 9, coupleId: 5, content: "Library", flipped: false, matched: false, language: "en"},
  { id: 10, coupleId: 5, content: "Biblioteca", flipped: false, matched: false, language: "es"},
  { id: 11, coupleId: 6, content: "Bookstore", flipped: false, matched: false, language: "en"},
  { id: 12, coupleId: 6, content: "Librería", flipped: false, matched: false, language: "es"},
  { id: 13, coupleId: 7, content: "Embarrassed", flipped: false, matched: false, language: "en"},
  { id: 14, coupleId: 7, content: "Avergonzado", flipped: false, matched: false, language: "es"},
  { id: 15, coupleId: 8, content: "Pregnant", flipped: false, matched: false, language: "en"},
  { id: 16, coupleId: 8, content: "Embarazada", flipped: false, matched: false, language: "es"},
  { id: 17, coupleId: 9, content: "Exit", flipped: false, matched: false, language: "en"},
  { id: 18, coupleId: 9, content: "Salida", flipped: false, matched: false, language: "es"},
  { id: 19, coupleId: 10, content: "Success", flipped: false, matched: false, language: "en"},
  { id: 20, coupleId: 10, content: "Éxito", flipped: false, matched: false, language: "es"},
];
